version: '2'
services:
    lnls-httpd:
        container_name: lnls-httpd
        image: gciotto/httpd-lnls
        ports:
            - 80:80
        volumes:
            - /home/opr24/docker-storage/lnls-httpd/:/var/www/html
